# Generated by Django 4.1.1 on 2024-01-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0003_about_me_bio_about_me_facebook_about_me_github_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50)),
                ("from_date", models.CharField(max_length=50)),
                ("to_date", models.CharField(max_length=50)),
                ("bio", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experience",
            },
        ),
    ]
