# Generated by Django 4.1.1 on 2024-01-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(),
        ),
    ]
