# Generated by Django 4.1.1 on 2024-01-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Website Color',
                'verbose_name_plural': 'Website Color',
            },
        ),
    ]
