# Generated by Django 4.1.1 on 2024-01-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_rename_course_name_project_language1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
